# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - JPEG_VERSION=8  LIBPNG_VERSION="1.6.22"  CONDA_PY=27
    - JPEG_VERSION=9  LIBPNG_VERSION="1.6.26"  CONDA_PY=27
    - JPEG_VERSION=8  LIBPNG_VERSION="1.6.22"  CONDA_PY=34
    - JPEG_VERSION=9  LIBPNG_VERSION="1.6.26"  CONDA_PY=34
    - JPEG_VERSION=8  LIBPNG_VERSION="1.6.22"  CONDA_PY=35
    - JPEG_VERSION=9  LIBPNG_VERSION="1.6.26"  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "i2ZUJV0gktmY2/T3XPrXI8aoat2+IIKii2/JLHCHSBBeaCIKrFeC8bADKZtVNfBc5LSqL8S+kzL3O7lH/kHOZVFSpkzpkKzzEUxuE1sbOQlpnijJlHN+RQ0DIl07Lt286mkMQoTHK6QjpnlHSyEKBWCJFkGk1IXZf4V+HfPessICFM6qC1iVeMRkaa0V2BWlXaeqgXR01pbIxdePP/9TNe/LhcoTSj45ZLsLJ4P0qXA3TH32ufJOTtxw5Q0trgh4hqBNKFQN+QCa+Lp8aDmljXFXNx5Qef/NAXftnK3uHy9qSD07P37xdUxBXaHgrpPuUflq0oOdjIPDPztAr5NgEPMipFlny5FCuTiwf3ywzwzMpei8KTiegwl02ycGInKot65ToxO/vj5WyOCKEj92V8ffveJutv/VdrerubylN6dYhCqrxnX/zm9Z43SYBkRV0L49GtxtvmxeQn9qPQmH+ZAAY2/LCx7wKKTI1ehW1MBMVYOr7Rx2d7wg8usV5tCV36tMgzuOr0ICutw5c4zvhIdiTVkmMqyNmJj4HF4HGR7tdBBjX6EbULXAiXIE8Ewe/QBXwOUVcDPfSEM2SLkI1bHAjiBCBfmvOtMf62vVQllztfrkqFvDPSvA8lLtosyuBZIjHtncr507vUHwd3xHeCjLx84YBL1J8J/h/K2OAuY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
