matrix:
  # default channel anaconda 4 requirements
- [[JPEG_VERSION, 8], [LIBPNG_VERSION, '"1.6.22"']]
  # conda-forge channel requirements.
- [[JPEG_VERSION, 9], [LIBPNG_VERSION, '"1.6.26"']]
travis:
  secure:
    BINSTAR_TOKEN: i2ZUJV0gktmY2/T3XPrXI8aoat2+IIKii2/JLHCHSBBeaCIKrFeC8bADKZtVNfBc5LSqL8S+kzL3O7lH/kHOZVFSpkzpkKzzEUxuE1sbOQlpnijJlHN+RQ0DIl07Lt286mkMQoTHK6QjpnlHSyEKBWCJFkGk1IXZf4V+HfPessICFM6qC1iVeMRkaa0V2BWlXaeqgXR01pbIxdePP/9TNe/LhcoTSj45ZLsLJ4P0qXA3TH32ufJOTtxw5Q0trgh4hqBNKFQN+QCa+Lp8aDmljXFXNx5Qef/NAXftnK3uHy9qSD07P37xdUxBXaHgrpPuUflq0oOdjIPDPztAr5NgEPMipFlny5FCuTiwf3ywzwzMpei8KTiegwl02ycGInKot65ToxO/vj5WyOCKEj92V8ffveJutv/VdrerubylN6dYhCqrxnX/zm9Z43SYBkRV0L49GtxtvmxeQn9qPQmH+ZAAY2/LCx7wKKTI1ehW1MBMVYOr7Rx2d7wg8usV5tCV36tMgzuOr0ICutw5c4zvhIdiTVkmMqyNmJj4HF4HGR7tdBBjX6EbULXAiXIE8Ewe/QBXwOUVcDPfSEM2SLkI1bHAjiBCBfmvOtMf62vVQllztfrkqFvDPSvA8lLtosyuBZIjHtncr507vUHwd3xHeCjLx84YBL1J8J/h/K2OAuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
